### ISSUE TITLE
Error between waiting and matched students

### ISSUE THREAD

**Issue by tremag** [Apexal/rpi-asc#8]
Hi Frank, I just logged off of the WebEx session and I believe I may have found a bug. (I didn't say anything because my mic is trash and I was digging through my filesystem to find the screenshot I took)
Best case there was only 1 student in the queue and the numbers were lying to me, but I figured I should mention it in case it's the worst-case scenario and there were 2 students in the queue but only 1 was showing up.
<img width="1440" alt="Screen Shot 2020-04-03 at 12 19 08 PM" src="https://user-images.githubusercontent.com/43757336/78399726-4c1bc580-75aa-11ea-9c60-f70901f8e1e1.png">

**Comment by Apexal** [comment]
This *might* be that an accepted student had "Text message" as their contact platform and it doesn't show all current students that option yet (I am fixing that now). I will dive into Firebase and see if I can make sure that was it! Good catch.

**Comment by Apexal** [comment]
Yep, this was due to an accepted student choose text messaging.
